//! Writes `src/Tables.mw` and `src/Cases.mw` for hex.
//!
//! ```text
//! cargo run --release -- <package root>
//! ```
//!
//! * **Tables** -- how Rust's `{:?}` writes each byte taken as a character,
//!   since the crate's error message quotes the offending one that way.
//! * **Cases** -- bytes encoded, and text decoded, valid and not, with what the
//!   crate makes of them.
//!
//! The library is ported by hand into `src/`, and the crate's source is
//! fingerprinted.

use std::fmt::Write as _;
use std::path::PathBuf;

/// The crate version pinned in `Cargo.toml`.
const UPSTREAM_VERSION: &str = "0.4.3";

/// The fingerprint of the crate's source, which `src/` ports.
const SOURCES: u64 = 0xefad_ef08_f466_0577;

fn main() {
    let root = PathBuf::from(std::env::args().nth(1).unwrap_or_else(|| "../..".into()));

    let print = fingerprint(include_str!(concat!(env!("OUT_DIR"), "/sources.rs.txt")));
    if print != SOURCES {
        eprintln!(
            "error: hex is not the version src/ ports.\n\
             Compare its source in {} with the previous version, carry any change\n\
             into src/, then set SOURCES in scripts/generate/src/main.rs to\n\
             {print:#x}",
            env!("UPSTREAM_DIR")
        );
        std::process::exit(1);
    }

    let tables = tables();
    let path = root.join("src/Tables.mw");
    std::fs::write(&path, &tables).unwrap();
    eprintln!("wrote {} ({} bytes)", path.display(), tables.len());

    let cases = cases();
    let path = root.join("src/Cases.mw");
    std::fs::write(&path, &cases).unwrap();
    eprintln!("wrote {} ({} bytes)", path.display(), cases.len());
}

/// FNV-1a: stable across builds, which `DefaultHasher` does not promise.
fn fingerprint(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in text.bytes() {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

// --- encoding -----------------------------------------------------------------------

/// A number as `digits` base-64 digits, most significant first, each digit the
/// character `'0' + d`: `'0'` to `'o'`, one contiguous run of ASCII.
fn digits(out: &mut String, value: u64, digits: u32) {
    assert!(
        value < 1 << (6 * digits),
        "{value} does not fit in {digits} digits"
    );
    for k in (0..digits).rev() {
        out.push(char::from(b'0' + ((value >> (6 * k)) & 63) as u8));
    }
}

/// A string, as its length in bytes (3 digits) and then its bytes.
fn text(out: &mut String, s: &str) {
    digits(out, s.len() as u64, 3);
    out.push_str(s);
}

/// Bytes, as a string of their hex digits.
fn bytes(out: &mut String, b: &[u8]) {
    let hex: String = b.iter().map(|x| format!("{x:02x}")).collect();
    text(out, &hex);
}

/// `text` as one Meadow string literal, broken with `\`-newline every `width`
/// characters. Only printable ASCII is written raw; a space that would start a
/// line is `\x20`, since a continuation drops leading whitespace.
fn long_literal(text: &str, width: usize) -> String {
    let mut out = String::with_capacity(text.len() + text.len() / width * 4 + 2);
    out.push('"');
    for (i, c) in text.chars().enumerate() {
        let line_start = i > 0 && i % width == 0;
        if line_start {
            out.push_str("\\\n    ");
        }
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            ' ' if line_start => out.push_str("\\x20"),
            ' '..='~' => out.push(c),
            _ => {
                let _ = write!(out, "\\u{{{:X}}}", u32::from(c));
            }
        }
    }
    out.push('"');
    out
}

const HEADER: &str = "\
-- Copyright (c) 2013-2014 The Rust Project Developers, (c) 2015-2020 The
-- rust-hex Developers, and the Meadow port's authors. Dual-licensed under
-- Apache-2.0 or MIT: see COPYRIGHT.";

// --- tables -------------------------------------------------------------------------

fn tables() -> String {
    let mut body = String::new();
    for b in 0..=255u8 {
        text(&mut body, &format!("{:?}", b as char));
    }
    format!(
        "-- GENERATED by scripts/generate.sh for hex {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
{HEADER}

-- How Rust's `{{:?}}` writes each byte, 0 to 255, taken as a character: each
-- entry its length (3 base-64 digits: '0' ('0' + 0) to 'o' ('0' + 63), most
-- significant first) and then the text.
@pub(pkg) def quotedBytes =
  {}
",
        long_literal(&body, 96)
    )
}

// --- cases --------------------------------------------------------------------------

/// A small deterministic generator, so that the cases are the same on every run.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }

    fn bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| self.next() as u8).collect()
    }
}

/// Text to decode: hex, often damaged with other bytes.
fn random_hex(rng: &mut Rng) -> Vec<u8> {
    let n = rng.below(24);
    let source = rng.bytes(n);
    let mut t = if rng.below(2) == 0 {
        hex::encode(&source)
    } else {
        hex::encode_upper(&source)
    }
    .into_bytes();
    for _ in 0..rng.below(4) {
        let at = rng.below(t.len() + 1);
        match rng.below(4) {
            0 if !t.is_empty() => {
                t.remove(at.min(t.len() - 1));
            }
            1 => t.insert(at, rng.next() as u8),
            2 => t.insert(at, b"gG xX-\n\0'\\"[rng.below(10)]),
            _ => t.insert(at, b"0123456789abcdefABCDEF"[rng.below(22)]),
        }
    }
    t
}

fn result<T>(out: &mut String, r: Result<T, hex::FromHexError>, ok: impl FnOnce(&mut String, T)) {
    match r {
        Ok(v) => {
            digits(out, 1, 1);
            ok(out, v);
        }
        Err(e) => {
            digits(out, 0, 1);
            text(out, &e.to_string());
        }
    }
}

fn cases() -> String {
    let mut rng = Rng(0x4e8_7a4a_c0ff_ee42);
    let mut body = String::new();
    let mut counts = [0usize; 2];

    // Kind 0: bytes encoded, and encoded into a slice of some length.
    for n in 0..40 {
        for _ in 0..10 {
            let input = rng.bytes(n);
            let slice = [2 * n, 2 * n + 1, 2 * n.saturating_sub(1), 0][rng.below(4)];
            counts[0] += 1;
            digits(&mut body, 0, 1);
            bytes(&mut body, &input);
            text(&mut body, &hex::encode(&input));
            text(&mut body, &hex::encode_upper(&input));
            digits(&mut body, slice as u64, 2);
            let mut out = vec![0u8; slice];
            result(
                &mut body,
                hex::encode_to_slice(&input, &mut out),
                |o, ()| text(o, &String::from_utf8(out.clone()).unwrap()),
            );
        }
    }

    // Kind 1: text decoded, and decoded into a slice of some length.
    for _ in 0..5000 {
        let input = random_hex(&mut rng);
        let slice = [input.len() / 2, input.len() / 2 + 1, 0][rng.below(3)];
        counts[1] += 1;
        digits(&mut body, 1, 1);
        bytes(&mut body, &input);
        result(&mut body, hex::decode(&input), |o, v| bytes(o, &v));
        digits(&mut body, slice as u64, 2);
        let mut out = vec![0u8; slice];
        let r = hex::decode_to_slice(&input, &mut out);
        result(&mut body, r, |o, ()| bytes(o, &out));
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from hex {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
-- Inputs, with what the crate makes of them, for `Tests.mw`: {} encodings and
-- {} decodings.
--
{HEADER}

-- Each case starts with its kind (1 base-64 digit), and its fields follow in
-- the order `Tests.mw` reads them. A string is its length in bytes (3 digits)
-- and then its bytes; bytes are a string of their hex digits; a result is 1
-- and the value, or 0 and the error message.
@cfg(test)
@pub(pkg) def cases =
  {}",
        counts[0],
        counts[1],
        long_literal(&body, 96)
    );
    out
}
